In [1]:
import numpy as np

In [2]:
a=np.zeros(10)

In [3]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
b=np.ones(10)

In [5]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
b*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
x=np.arange(10,51)

In [9]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
y=np.arange(10,51,2)

In [11]:
y

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
b=np.arange(0,9)

In [13]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.rand(1)

array([0.34695884])

In [19]:
np.random.randn(5,5)

array([[ 0.00965947,  0.9791587 ,  0.09362222, -0.04340449, -2.12975586],
       [-0.31640259, -0.63558286,  0.44041244, -1.44781403,  1.14435928],
       [ 0.12052328, -0.37804008, -0.6678288 ,  0.3178768 , -0.65250556],
       [-1.13362439,  0.0861755 , -0.82948214,  0.88520798, -1.28080558],
       [ 0.02715622, -0.31681597, -0.44903497, -0.18456903, -1.61552778]])

In [21]:
np.random.rand(10,10)

array([[0.96515453, 0.44546395, 0.63254543, 0.93838878, 0.68735673,
        0.87836689, 0.86804736, 0.14971557, 0.81713324, 0.83552478],
       [0.33564036, 0.20545157, 0.91108289, 0.52947917, 0.94780153,
        0.33478735, 0.85889117, 0.12118516, 0.32737738, 0.01341646],
       [0.59291958, 0.01112597, 0.32818665, 0.62675978, 0.58718111,
        0.83380763, 0.73890473, 0.89426809, 0.07152844, 0.60175047],
       [0.41342659, 0.56427132, 0.21106642, 0.22970954, 0.74999315,
        0.05044531, 0.8786941 , 0.37449854, 0.15408299, 0.66827591],
       [0.41196821, 0.336141  , 0.37317194, 0.23294076, 0.8272775 ,
        0.3865426 , 0.70183767, 0.84774509, 0.46104056, 0.0647015 ],
       [0.03563622, 0.3361116 , 0.83964193, 0.65772897, 0.01828945,
        0.09568145, 0.24281408, 0.4248373 , 0.7795008 , 0.92719464],
       [0.13774975, 0.04902413, 0.28699061, 0.54087893, 0.04045142,
        0.1029871 , 0.27710561, 0.55226021, 0.03947848, 0.0721933 ],
       [0.89267521, 0.8620566 , 0.6349956

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [23]:
x=np.arange(1,26).reshape(5,5)

In [24]:
#slicing of numpy arrays
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
x[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
x[3,4]

20

In [35]:
x[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [34]:
x[4,:]

array([21, 22, 23, 24, 25])

In [29]:
x[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
#useful methods for finding min and max
x.sum()

325

In [31]:
x.std()

7.211102550927978

In [32]:
x.sum(axis=1)

array([ 15,  40,  65,  90, 115])